<?php
header('Content-Type: text/css; charset=utf-8');
require_once '../includes/config.php';

// ⭐ دریافت تنظیمات از دیتابیس
$settings = [];
$res = mysqli_query($conn, "SELECT * FROM theme_settings");
if ($res) {
    while ($r = mysqli_fetch_assoc($res)) {
        $settings[$r['setting_name']] = $r['setting_value'];
    }
}

// ⭐ مقادیر پیش‌فرض
$defaults = [
    'primary_color'     => '#d4af37',
    'bg_color'          => '#0a0f1a',
    'surface_color'     => '#151a25',
    'border_color'      => '#1e2533',
    'text_color'        => '#e8ecf1',
    'text_secondary'    => '#8899aa',
    'accent_color'      => '#4b8cf7',
    'green_color'       => '#10b981',
    'red_color'         => '#ef4444',
    'purple_color'      => '#8b5cf6',
    'amber_color'       => '#f0a040',
    'btn_bg'            => '#4b8cf7',
    'btn_text'          => '#ffffff',
    'header_bg'         => '#151a25',
    'icon_color'        => '#d4af37',
    'input_bg'          => '#1a1f2e',
    'input_border'      => '#2a3040',
    'shadow_color'      => '#000000',
];

// ⭐ ترکیب با مقادیر ذخیره شده
$c = array_merge($defaults, $settings);
?>
/* ============================================
   Dynamic Theme - تراز روزانه
   Generated by dynamic-theme.php
   ============================================ */

:root {
    /* رنگ‌های اصلی */
    --gold: <?php echo $c['primary_color']; ?>;
    --gold-light: <?php echo $c['primary_color']; ?>;
    --bg: <?php echo $c['bg_color']; ?>;
    --surface: <?php echo $c['surface_color']; ?>;
    --border: <?php echo $c['border_color']; ?>;
    --text: <?php echo $c['text_color']; ?>;
    --text-secondary: <?php echo $c['text_secondary']; ?>;
    --accent: <?php echo $c['accent_color']; ?>;
    
    /* رنگ‌های وضعیت */
    --green: <?php echo $c['green_color']; ?>;
    --red: <?php echo $c['red_color']; ?>;
    --purple: <?php echo $c['purple_color']; ?>;
    --amber: <?php echo $c['amber_color']; ?>;
    
    /* پس‌زمینه‌های رنگی */
    --green-bg: <?php echo $c['green_color']; ?>15;
    --red-bg: <?php echo $c['red_color']; ?>15;
    --purple-bg: <?php echo $c['purple_color']; ?>15;
    --amber-bg: <?php echo $c['amber_color']; ?>15;
    
    /* المان‌ها */
    --btn-bg: <?php echo $c['btn_bg']; ?>;
    --btn-text: <?php echo $c['btn_text']; ?>;
    --header-bg: <?php echo $c['header_bg']; ?>;
    --icon-color: <?php echo $c['icon_color']; ?>;
    --input-bg: <?php echo $c['input_bg']; ?>;
    --input-border: <?php echo $c['input_border']; ?>;
    --shadow: <?php echo $c['shadow_color']; ?>;
    
    /* مقادیر ثابت */
    --radius-sm: 8px;
    --radius: 14px;
    --radius-lg: 18px;
}

/* ============================================
   تم روشن (Light Mode)
   ============================================ */
body.light {
    --gold: #b8960f;
    --gold-light: #8b6914;
    --bg: #f5f6f8;
    --surface: #ffffff;
    --border: #d0d7de;
    --text: #1a1f2e;
    --text-secondary: #555f6e;
    --accent: #3b6fd4;
    
    --green: #16a34a;
    --red: #dc2626;
    --purple: #7c3aed;
    --amber: #d97706;
    
    --green-bg: #f0fdf4;
    --red-bg: #fef2f2;
    --purple-bg: #f5f3ff;
    --amber-bg: #fffbeb;
    
    --btn-bg: #3b6fd4;
    --btn-text: #ffffff;
    --header-bg: #ffffff;
    --icon-color: #b8960f;
    --input-bg: #f6f8fa;
    --input-border: #d0d7de;
    --shadow: #00000015;
    
    background-image: none !important;
}

/* استایل‌های عمومی */
body {
    background: var(--bg);
    color: var(--text);
    transition: background 0.3s, color 0.3s;
}

/* کارت‌ها */
.card, .section-card, .archive-card, .welcome-card, .feed-card {
    background: var(--surface);
    border: 1px solid var(--border);
    box-shadow: 0 2px 8px var(--shadow);
}

/* دکمه‌ها */
.btn, button, .btn-icon, .btn-calc, .btn-export, .btn-save, .btn-pdf, .btn-gen,
.btn-primary, .btn-danger, .btn-success, .btn-warning, .btn-new, .btn-new-day,
.btn-print, .btn-print-official, .btn-date-action, .btn-confirm {
    transition: all 0.2s;
}

.btn:hover, button:hover, .btn-icon:hover {
    opacity: 0.9;
    transform: translateY(-1px);
}

/* Input ها */
input, textarea, select {
    background: var(--input-bg);
    border: 1px solid var(--input-border);
    color: var(--text);
    transition: border-color 0.2s;
}

input:focus, textarea:focus, select:focus {
    border-color: var(--accent);
    outline: none;
}

/* هدر */
.header, .app-header {
    background: var(--header-bg);
    border: 1px solid var(--border);
}

/* آیکون‌ها */
.icon, [class*="icon-"] {
    color: var(--icon-color);
}

/* جداول */
table th {
    background: var(--surface);
    color: var(--text-secondary);
}

table td {
    border-color: var(--border);
}

/* پیام‌ها و toast */
.toast.success { background: var(--green); }
.toast.error { background: var(--red); }

/* Scrollbar */
::-webkit-scrollbar { width: 6px; }
::-webkit-scrollbar-track { background: transparent; }
::-webkit-scrollbar-thumb { 
    background: var(--border); 
    border-radius: 3px;
}
::-webkit-scrollbar-thumb:hover { background: var(--text-secondary); }

/* Selection */
::selection {
    background: var(--accent);
    color: white;
}

body.light {
    background-image: none !important;
    background-color: var(--bg) !important;
}